### ISSUE TITLE
[Bug]: Several Controlnet preprocessors are non-functional 

### ISSUE THREAD

**Issue by Aiboi-png** [Panchovix/stable-diffusion-webui-reForge#269]
### Checklist

- [x] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

Note: I did not disable any of  the extensions that came with reForge.
### What happened?

Several integrated controlnet preprocessors fail to run/download. While the error in console is the same from some of the preprocessors, it is not the same for all preprocessors.

### Steps to reproduce the problem

1. Put any image into controlnet
2. Select any of the following controlnet preprocessors: "depth_anything_v2"  "normalbae" "normal_bae_variant" "scribble_pidinet" "seg_ofade20k" "seg_ufade20k" "seg_ofcoco" "scribble_pidinet" "softedge_pidinet" "softedge_pidisafe"
3. Attempt to run any of the noted preprocessors

### What should have happened?

The preprocessor should run on the image.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2025-02-13-01-22.json](https://github.com/user-attachments/files/18776046/sysinfo-2025-02-13-01-22.json)

### Console logs

```Shell
The end error varies between some of the preprocessors. I have had other people with up-to-date UI's attempt to run at least some of the listed preprocessors, and they get the same error. The following is a log from starting and attempting to run "depth_anything_v2":

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.6.5dev-v1.10.1RC-latest-2030-geda0ce59
Commit hash: eda0ce597761d6c823b91c777e3f65021b281948
E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
E:\Data\Packages\SDRF\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --gradio-allowed-path 'E:\Data\Images'
Total VRAM 24564 MB, total RAM 130262 MB
pytorch version: 2.3.1+cu121
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for speed improvements if having 16GB or more VRAM. It may cause issues with 12GB VRAM or less.
Hint: your device supports --cuda-malloc for a bit less vram usage and small speed improvement
Hint: your device supports --cuda-stream for potential speed improvements but it may cause issues on some GPUs that have 6-8GB VRAM or less.
VAE dtype: [torch.bfloat16, torch.bfloat16, torch.float16, torch.float32]
E:\Data\Packages\SDRF\modules_forge\initialization.py:55: UserWarning: expandable_segments not supported on this platform (Triggered internally at ..\c10/cuda/CUDAAllocatorConfig.h:28.)
  torch.zeros((1, 1)).to(device, torch.float32)
CUDA Stream Activated:  False
Using pytorch attention
ControlNet preprocessor location: E:\Data\Packages\SDRF\models\ControlNetPreprocessor
Loading weights [31e35c80fc] from E:\Data\Packages\SDRF\models\Stable-diffusion\sd\sd_xl_base_1.0.safetensors
2025-02-12 17:25:50,927 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.0s (prepare environment: 3.7s, import torch: 3.4s, import gradio: 0.5s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.3s, load scripts: 3.1s, create ui: 2.1s, gradio launch: 0.8s).
WARNING:root:clip missing: ['clip_l.text_projection', 'clip_l.logit_scale']
Model loaded in 5.7s (load weights from disk: 0.2s, forge instantiate config: 1.2s, forge load real models: 3.8s, calculate empty prompt: 0.5s).
2025-02-12 17:26:07,456 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Data\Packages\SDRF\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 929, in run_annotator
    result = preprocessor(
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
    result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 218, in depth_anything_v2
    from annotator.depth_anything_v2 import DepthAnythingV2Detector
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\depth_anything_v2.py", line 9, in <module>
    from depth_anything_v2.dpt import DepthAnythingV2
ModuleNotFoundError: No module named 'depth_anything_v2'

----------------------------------------------------------------------------------------------------------------------
The following log is from starting and running "seg_ofade20k"


Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.6.5dev-v1.10.1RC-latest-2030-geda0ce59
Commit hash: eda0ce597761d6c823b91c777e3f65021b281948
E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
E:\Data\Packages\SDRF\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --gradio-allowed-path 'E:\Data\Images'
Total VRAM 24564 MB, total RAM 130262 MB
pytorch version: 2.3.1+cu121
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for speed improvements if having 16GB or more VRAM. It may cause issues with 12GB VRAM or less.
Hint: your device supports --cuda-malloc for a bit less vram usage and small speed improvement
Hint: your device supports --cuda-stream for potential speed improvements but it may cause issues on some GPUs that have 6-8GB VRAM or less.
VAE dtype: [torch.bfloat16, torch.bfloat16, torch.float16, torch.float32]
E:\Data\Packages\SDRF\modules_forge\initialization.py:55: UserWarning: expandable_segments not supported on this platform (Triggered internally at ..\c10/cuda/CUDAAllocatorConfig.h:28.)
  torch.zeros((1, 1)).to(device, torch.float32)
CUDA Stream Activated:  False
Using pytorch attention
ControlNet preprocessor location: E:\Data\Packages\SDRF\models\ControlNetPreprocessor
Loading weights [31e35c80fc] from E:\Data\Packages\SDRF\models\Stable-diffusion\sd\sd_xl_base_1.0.safetensors
2025-02-12 17:30:08,374 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.5s (prepare environment: 3.9s, import torch: 3.4s, import gradio: 0.5s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.3s, load scripts: 3.2s, create ui: 2.1s, gradio launch: 0.8s).
WARNING:root:clip missing: ['clip_l.text_projection', 'clip_l.logit_scale']
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 243, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\routes.py", line 604, in join_queue
    session_info = await asyncio.wait_for(
  File "asyncio\tasks.py", line 445, in wait_for
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1001
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 243, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\routes.py", line 604, in join_queue
    session_info = await asyncio.wait_for(
  File "asyncio\tasks.py", line 445, in wait_for
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1001
Model loaded in 5.8s (load weights from disk: 0.2s, forge instantiate config: 1.2s, forge load real models: 3.8s, calculate empty prompt: 0.6s).
2025-02-12 17:30:36,705 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Data\Packages\SDRF\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 929, in run_annotator
    result = preprocessor(
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
    result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 607, in oneformer_coco
    from annotator.oneformer import OneformerDetector
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\__init__.py", line 4, in <module>
    from .api import make_detectron2_model, semantic_run
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\api.py", line 7, in <module>
    from annotator.oneformer.detectron2.projects.deeplab import add_deeplab_config
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\projects\deeplab\__init__.py", line 4, in <module>
    from .resnet import build_resnet_deeplab_backbone
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\projects\deeplab\resnet.py", line 6, in <module>
    from annotator.oneformer.detectron2.modeling import BACKBONE_REGISTRY
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\modeling\__init__.py", line 20, in <module>
    from .meta_arch import (
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\modeling\meta_arch\__init__.py", line 6, in <module>
    from .panoptic_fpn import PanopticFPN
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\modeling\meta_arch\panoptic_fpn.py", line 14, in <module>
    from .rcnn import GeneralizedRCNN
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\modeling\meta_arch\rcnn.py", line 9, in <module>
    from annotator.oneformer.detectron2.data.detection_utils import convert_image_to_rgb
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\data\__init__.py", line 2, in <module>
    from . import transforms  # isort:skip
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\data\transforms\__init__.py", line 4, in <module>
    from .transform import *
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\data\transforms\transform.py", line 36, in <module>
    class ExtentTransform(Transform):
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\oneformer\detectron2\data\transforms\transform.py", line 46, in ExtentTransform
    def __init__(self, src_rect, output_size, interp=Image.LINEAR, fill=0):
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'
```

### Additional information

While all testing during the creation of this report was done on a fresh install dev, I have encountered the same errors on main. The segmentation preprocessors work on version `f1.2.5-v1.10.1RC-latest-983-g44e5eb17` but I am unsure as the the version in which they break. I installed and am running reForge via Stability Matrix, but I do not believe that to be the issue given that the older version of reForge that the segmentation preprocessor worked on was also installed and ran via Stability Matrix, but it was also done on another machine.

**Comment by Panchovix** [comment]
Hi there, both should be fixed now on latest commits.

Depth anything v2 issue was because it was not installing the library automatically

And the AttributeError: module 'PIL.Image' has no attribute 'LINEAR' it's because now it uses .BILINEAR instead of LINEAR.

Not sure how stability matrix does it updates, but on my side could replicate and now the issue are not there.

You can re open if you find any issues.

**Comment by Aiboi-png** [comment]
Thanks! A few of them still don't work. The following is a list of preprocessors that still error and the error's they throw. Note: This are just the errors that are thrown when attempting to run, and not the whole dump from start.

"normal_bae_variant"
```2025-02-13 17:53:09,680 - ControlNet - INFO - Preview Resolution = 680
Traceback (most recent call last):
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 903, in run_annotator
    result = preprocessor(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
    result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
TypeError: cannot unpack non-iterable NoneType object```

**Comment by Aiboi-png** [comment]
"scribble_pidinet"

```2025-02-13 17:54:19,061 - ControlNet - INFO - Preview Resolution = 680
Traceback (most recent call last):
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 903, in run_annotator
    result = preprocessor(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
    result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 382, in scribble_pidinet
    result, _ = pidinet(img, res)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 355, in pidinet
    from annotator.pidinet import apply_pidinet
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\pidinet\__init__.py", line 5, in <module>
    from annotator.pidinet.model import pidinet
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\pidinet\model.py", line 14, in <module>
    from basicsr.utils import img2tensor
ModuleNotFoundError: No module named 'basicsr'```

**Comment by Aiboi-png** [comment]
"seg_ufade20k"

```2025-02-13 17:56:28,989 - ControlNet - INFO - Preview Resolution = 680
Traceback (most recent call last):
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\inference.py", line 5, in <module>
    import mmcv as mmcv
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 903, in run_annotator
    result = preprocessor(
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
    result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 335, in uniformer
    from annotator.uniformer import apply_uniformer
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\__init__.py", line 4, in <module>
    from annotator.uniformer.inference import init_segmentor, inference_segmentor, show_result_pyplot
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\inference.py", line 11, in <module>
    import annotator.mmpkg.mmcv as mmcv
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\__init__.py", line 4, in <module>
    from .fileio import *
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\fileio\file_client.py", line 15, in <module>
    from annotator.mmpkg.mmcv.utils.misc import has_method
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\utils\__init__.py", line 3, in <module>
    from .config import Config, ConfigDict, DictAction
  File "E:\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\utils\config.py", line 16, in <module>
    from addict import Dict
ModuleNotFoundError: No module named 'addict'```

**Comment by Panchovix** [comment]
Hi there, thanks for the reports. Can you try for me, in your venv, do

`pip install basicsr addict`

And see scribble_pidinet and seg_ufade20k work? I'm not home now, so I can't test directly for now.

**Comment by Aiboi-png** [comment]
> Hi there, thanks for the reports. Can you try for me, in your venv, do
> 
> `pip install basicsr addict`
> 
> And see scribble_pidinet and seg_ufade20k work? I'm not home now, so I can't test directly for now.

Sure, I'll try right now

**Comment by Aiboi-png** [comment]
It does not appear to fix the issue. Note: I did this on my dev branch install rather than the main one that I use. While the command appears to run successfully in the cmd window, the following error is thrown when attempting to run ufade20k:

```2025-02-13 18:24:42,464 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\inference.py", line 5, in <module>
    import mmcv as mmcv
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Data\Packages\SDRF\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Data\Packages\SDRF\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 929, in run_annotator
    result = preprocessor(
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
    result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 335, in uniformer
    from annotator.uniformer import apply_uniformer
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\__init__.py", line 4, in <module>
    from annotator.uniformer.inference import init_segmentor, inference_segmentor, show_result_pyplot
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\inference.py", line 11, in <module>
    import annotator.mmpkg.mmcv as mmcv
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\__init__.py", line 4, in <module>
    from .fileio import *
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\fileio\file_client.py", line 15, in <module>
    from annotator.mmpkg.mmcv.utils.misc import has_method
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\utils\__init__.py", line 3, in <module>
    from .config import Config, ConfigDict, DictAction
  File "E:\Data\Packages\SDRF\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\utils\config.py", line 16, in <module>
    from addict import Dict
ModuleNotFoundError: No module named 'addict'

**Comment by Aiboi-png** [comment]
The same error as last time for scribble also is thrown.

Also, I don't have the permissions to reopen this.

**Comment by Panchovix** [comment]
Those requiring mmcv is a lot haha, can you try installing it? It's prob not trivial if it doesn't work at first try.

Re opening then.

**Comment by Panchovix** [comment]
No problem. When I have time and in home I will try. Probably some of these are added after forge was created, so support for them have to be added or fixed. (I did port some of them directly without much testing)

**Comment by Seshelle** [comment]
Tried it for AiBoi, got this error
```
(venv) PS C:\Users\Owner\Documents\Stability Matrix\Data\Packages\Stable Diffusion WebUI reForge> pip install basicsr addict
Fatal error in launcher: Unable to create process using '"C:\Users\Owner\Downloads\Data\Packages\Stable Diffusion WebUI reForge\venv\Scripts\python.exe"  "C:\Users\Owner\Documents\Stability Matrix\Data\Packages\Stable Diffusion WebUI reForge\venv\Scripts\pip.exe" install basicsr addict': The system cannot find the file specified.
```
