### ISSUE TITLE
[Bug]: SyntaxWarning: invalid escape sequence in prompt_parser.py:383

### ISSUE THREAD

**Issue by aoleg** [Panchovix/stable-diffusion-webui-reForge#396]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After the last commit, I am getting a Syntax Warning on startup. While reForge seemingly skips through the issue and generates normally, this is not something that should be happening. I am not sure which of the latest commits caused this, most likely something during the last day or two.

It is likely that the issue is caused by https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/465bb736eb8fbb34295e45e2443dff3afe0894db

### Steps to reproduce the problem

Launch reForge. The warning will appear in the console log.

### What should have happened?

No warning.

### Sysinfo

https://pastebin.com/vePu2uq8

### Console logs

```Shell
venv "S:\stable-diffusion\stable-diffusion-webui-reForge-dev\webui\venv\Scripts\Python.exe"
Python 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
Version: f1.0.0v2dev-v1.10.1RC-latest-2443-gd6f13b7d
Commit hash: d6f13b7d2338d269081e552c7c5ce2de054bfc5d
Launching Web UI with arguments: --skip-install --cuda-malloc --pin-shared-memory --cuda-stream --allow-fp16-accumulation --theme dark --no-prompt-history --embeddings-dir 'S:\Models\embeddings' --models-dir 'S:\Models\models' --ckpt-dir 'S:\Models\Stable-Diffusion' --lora-dir 'S:\Models\Loras' --clip-models-path 'S:\.cache'
Using cudaMallocAsync backend.
Total VRAM 32607 MB, total RAM 65307 MB
pytorch version: 2.9.0.dev20250716+cu128
FP16 accumulation flag found, current state: False
FP16 accumulation set to: True
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
CUDA Stream Activated:  True
W0729 10:11:41.585000 22004 venv\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
Using pytorch attention
S:\stable-diffusion\stable-diffusion-webui-reForge-dev\webui\modules\prompt_parser.py:383: SyntaxWarning: invalid escape sequence '\('
  """
```

**Comment by Panchovix** [comment]
Thanks, should be fixed after https://github.com/Panchovix/stable-diffusion-webui-reForge/pull/395. If not let me know.

**Comment by aoleg** [comment]
Not fixed, just migrated to a different line number:

S:\stable-diffusion\stable-diffusion-webui-reForge-dev\webui\modules\prompt_parser.py:386: SyntaxWarning: invalid escape sequence '\('
  """


venv "S:\stable-diffusion\stable-diffusion-webui-reForge-dev\webui\venv\Scripts\Python.exe"
Python 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
Version: f1.0.0v2dev-v1.10.1RC-latest-2450-gc55c29fe
Commit hash: c55c29fe6f907af17208b92f5f0c52671970d4bf
Launching Web UI with arguments: --skip-install --cuda-malloc --pin-shared-memory --cuda-stream --allow-fp16-accumulation --theme dark --no-prompt-history --embeddings-dir 'S:\Models\embeddings' --models-dir 'S:\Models\models' --ckpt-dir 'S:\Models\Stable-Diffusion' --lora-dir 'S:\Models\Loras' --clip-models-path 'S:\.cache'
Using cudaMallocAsync backend.
Total VRAM 32607 MB, total RAM 65307 MB
pytorch version: 2.9.0.dev20250716+cu128
FP16 accumulation flag found, current state: False
FP16 accumulation set to: True
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync
CUDA Stream Activated:  True
W0729 22:37:20.745000 43796 venv\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
Using pytorch attention
S:\stable-diffusion\stable-diffusion-webui-reForge-dev\webui\modules\prompt_parser.py:386: SyntaxWarning: invalid escape sequence '\('
  """
